version: '3.8'

services:
    php-fpm:
        build: ./docker/php
        container_name: php_cfp_test
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        networks:
            - cfp-network
        extra_hosts:
            - host.docker.internal:host-gateway

    pgsql:
        image: postgres:15
        container_name: pgsql_cfp_test
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - cfp-test-pgsql:/var/lib/postgresql/data
            - ./docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/create-testing-database.sql
        networks:
            - cfp-network

    nginx:
        image: nginx:alpine
        container_name: nginx_cfp_test
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/var/www/app
            - ./docker/nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt
            - ./docker/nginx/ssl/localhost.key:/etc/ssl/private/localhost.key
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - cfp-network

    node:
        build: ./docker/node
        container_name: node_cfp_test
        ports:
            - '5173:5173'
        volumes:
            - ../front/:/var/www/app/
        working_dir: /var/www/app
        networks:
            - cfp-network
        extra_hosts:
            - host.docker.internal:host-gateway

networks:
    cfp-network:
        driver: bridge

volumes:
    cfp-test-pgsql:
        driver: local
