version: '3.8'

services:
    php:
        build: ./docker/php
        container_name: php_cfp_test
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        networks:
            - cfp-network
        extra_hosts:
            - host.docker.internal:host-gateway

    pgsql:
        image: postgres:15
        container_name: pgsql_cfp_test
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - cfp-test-pgsql:/var/lib/postgresql/data
        networks:
            - cfp-network

networks:
    cfp-network:
        driver: bridge

volumes:
    cfp-test-pgsql:
        driver: local
